config/routes.rb
Rails.application.routes.draw do
  resources :responses
  resources :topics
  resources :creators
  resources :hm_reviews
  root to:'home#index'
  post 'responses/create' => 'responses#create', as: :response_create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/hm_review.rb
class HmReview < ApplicationRecord
end

app/models/response.rb
class Response < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :set_creator, only: [:show, :edit, :update, :destroy]

  # GET /creators
  # GET /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1
  # GET /creators/1.json
  def show
  end

  # GET /creators/new
  def new
    @creator = Creator.new
  end

  # GET /creators/1/edit
  def edit
  end

  # POST /creators
  # POST /creators.json
  def create
    @creator = Creator.new(creator_params)

    respond_to do |format|
      if @creator.save
        format.html { redirect_to @creator, notice: 'Creator was successfully created.' }
        format.json { render :show, status: :created, location: @creator }
      else
        format.html { render :new }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creators/1
  # PATCH/PUT /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to @creator, notice: 'Creator was successfully updated.' }
        format.json { render :show, status: :ok, location: @creator }
      else
        format.html { render :edit }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1
  # DELETE /creators/1.json
  def destroy
    @creator.destroy
    respond_to do |format|
      format.html { redirect_to creators_url, notice: 'Creator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creator_params
      params.require(:creator).permit(:name, :type, :url)
    end
end

app/controllers/hm_reviews_controller.rb
class HmReviewsController < ApplicationController
  before_action :set_hm_review, only: [:show, :edit, :update, :destroy]

  # GET /hm_reviews
  # GET /hm_reviews.json
  def index
    @hm_reviews = HmReview.all
  end

  # GET /hm_reviews/1
  # GET /hm_reviews/1.json
  def show
    @hm_review = HmReview.find(params[:id])
  end

  # GET /hm_reviews/new
  def new
    @hm_review = HmReview.new
  end

  # GET /hm_reviews/1/edit
  def edit
  end

  # POST /hm_reviews
  # POST /hm_reviews.json
  def create
    @hm_review = HmReview.new(hm_review_params)

    respond_to do |format|
      if @hm_review.save
        format.html { redirect_to @hm_review, notice: 'Hm review was successfully created.' }
        format.json { render :show, status: :created, location: @hm_review }
      else
        format.html { render :new }
        format.json { render json: @hm_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hm_reviews/1
  # PATCH/PUT /hm_reviews/1.json
  def update
    respond_to do |format|
      if @hm_review.update(hm_review_params)
        format.html { redirect_to @hm_review, notice: 'Hm review was successfully updated.' }
        format.json { render :show, status: :ok, location: @hm_review }
      else
        format.html { render :edit }
        format.json { render json: @hm_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hm_reviews/1
  # DELETE /hm_reviews/1.json
  def destroy
    @hm_review.destroy
    respond_to do |format|
      format.html { redirect_to hm_reviews_url, notice: 'Hm review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hm_review
      @hm_review = HmReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hm_review_params
      params.require(:hm_review).permit(:hm_name, :hm_creator, :hm_comment, :hm_point, :created_at, :updated_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(params[:response].permit(:topic_id, :name, :body))
    @response.save
    redirect_to topic_path(params[:response]['topic_id'])
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:topic_id,:name, :body, :created_at, :updated_at)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @newTopic = Topic.new
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
      @newResponse = Response.new(:topic_id => params[:id])
      @responses = Response.where(topic_id: params[:id])
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :created_at, :updated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/hm_reviews_helper.rb
module HmReviewsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/creators/_form.html.erb
<%= form_with(model: creator, local: true) do |form| %>
  <% if creator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(creator.errors.count, "error") %> prohibited this creator from being saved:</h2>

      <ul>
      <% creator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/creators/edit.html.erb
<h1>Editing Creator</h1>

<%= render 'form', creator: @creator %>

<%= link_to 'Show', @creator %> |
<%= link_to 'Back', creators_path %>

app/views/creators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Creators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creators.each do |creator| %>
      <tr>
        <td><%= creator.name %></td>
        <td><%= creator.type %></td>
        <td><%= creator.url %></td>
        <td><%= link_to 'Show', creator %></td>
        <td><%= link_to 'Edit', edit_creator_path(creator) %></td>
        <td><%= link_to 'Destroy', creator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creator', new_creator_path %>
<%= link_to 'HOME', root_path %>

app/views/creators/new.html.erb
<h1>New Creator</h1>

<%= render 'form', creator: @creator %>

<%= link_to 'Back', creators_path %>

app/views/creators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @creator.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @creator.type %>
</p>

<p>
  <strong>Url:</strong>
  <%= @creator.url %>
</p>

<%= link_to 'Edit', edit_creator_path(@creator) %> |
<%= link_to 'Back', creators_path %>

app/views/hm_reviews/_form.html.erb
<%= form_with(model: hm_review, local: true) do |form| %>
  <% if hm_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hm_review.errors.count, "error") %> prohibited this hm_review from being saved:</h2>

      <ul>
      <% hm_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hm_name %>
    <%= form.text_field :hm_name %>
  </div>

  <div class="field">
    <%= form.label :hm_creator %>
    <%= form.text_field :hm_creator %>
  </div>

  <div class="field">
    <%= form.label :hm_comment %>
    <%= form.text_field :hm_comment %>
  </div>

  <div class="field">
    <%= form.label :hm_point %>
    <%= form.text_field :hm_point %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hm_reviews/edit.html.erb
<h1>Editing Hm Review</h1>

<%= render 'form', hm_review: @hm_review %>

<%= link_to 'Show', @hm_review %> |
<%= link_to 'Back', hm_reviews_path %>

app/views/hm_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hm Reviews</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>creator</th>
      <th>comment</th>
      <th>point</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hm_reviews.each do |hm_review| %>
      <tr>
        <td><%= hm_review.hm_name %></td>
        <td><%= hm_review.hm_creator %></td>
        <td><%= hm_review.hm_comment %></td>
        <td><%= hm_review.hm_point %></td>
        <td><%= hm_review.created_at %></td>
        <td><%= hm_review.updated_at %></td>
        <td><%= link_to 'Show', hm_review %></td>
        <td><%= link_to 'Edit', edit_hm_review_path(hm_review) %></td>
        <td><%= link_to 'Destroy', hm_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hm Review', new_hm_review_path %>
<%= link_to 'HOME', root_path %>

app/views/hm_reviews/new.html.erb
<h1>New Hm Review</h1>

<%= render 'form', hm_review: @hm_review %>

<%= link_to 'Back', hm_reviews_path %>

app/views/hm_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hm name:</strong>
  <%= @hm_review.hm_name %>
</p>

<p>
  <strong>Hm creator:</strong>
  <%= @hm_review.hm_creator %>
</p>

<p>
  <strong>Hm comment:</strong>
  <%= @hm_review.hm_comment %>
</p>

<p>
  <strong>Hm point:</strong>
  <%= @hm_review.hm_point %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @hm_review.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @hm_review.updated_at %>
</p>

<%= link_to 'Edit', edit_hm_review_path(@hm_review) %> |
<%= link_to 'Back', hm_reviews_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<!--[if IE 7 ]><html class="ie ie7 lte9 lte8 lte7" lang="en-US"><![endif]-->
<!--[if IE 8]><html class="ie ie8 lte9 lte8" lang="en-US">	<![endif]-->
<!--[if IE 9]><html class="ie ie9 lte9" lang="en-US"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="noIE" lang="en-US">
<!--<![endif]-->
	<head>
		<title>HandMade Review</title>

		<!-- meta -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no"/>

		<!-- google fonts -->
		<link href='http://fonts.googleapis.com/css?family=Raleway:500,300' rel='stylesheet' type='text/css'>
		<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans'>
		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Serif:regular,bold"/>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="assets/js/html5shiv.js"></script>
			<script src="assets/js/respond.js"></script>
		<![endif]-->

		<!--[if IE 8]>
	    	<script src="assets/js/selectivizr.js"></script>
	    <![endif]-->
	</head>

	<body>
		<header class="top-header">
			<div class="container">
				<div class="row">
					<div class="col-md-3 col-xs-5 col-sm-4 header-logo">
						<br>
					</div>

					<div class="col-md-8 col-md-offset-1 col-xs-7">
						<nav class="navbar navbar-default">
					  	<div class="container-fluid nav-bar">
					    <!-- Brand and toggle get grouped for better mobile display -->
							<!--
						    <div class="navbar-header">
						      	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							        <span class="sr-only">Toggle navigation</span>
							        <span class="icon-bar"></span>
							        <span class="icon-bar"></span>
							        <span class="icon-bar"></span>
						      	</button>
						    </div>
									-->
					    	<!-- Collect the nav links, forms, and other content for toggling -->
								<div id="gnavi" class="collapse navbar-collapse">
								  <ul class="nav navbar-nav">
							      <li>
											<a href="/"><font color="#000080"><i class="fa fa-home top-fa-color"></i> Home</font></a>
										</li>
										<li>
											<a href="/hm_reviews"><font color="#000080"><i class="fa fa-star top-fa-color"></i> Reviews</font></a>
										</li>
										<li>
											<a href="/creators"><font color="#000080"><i class="fa fa-users top-fa-color"></i> Creators</font></a>
										</li>
										<li>
											<a href="/topics"><font color="#000080"><i class="fa fa-tasks top-fa-color"></i> 掲示板</font></a>
										</li>
										<li>
											<a href="/pages/relatednews"><font color="#000080"><i class="fa fa-wordpress top-fa-color"></i> 関連ニュース</font></a>
										</li>
						      </ul>
						    </div><!-- /navbar-collapse -->
					  	</div><!-- / .container-fluid -->
						</nav>
					</div>
				</div>
			</div>
		</header>

		<div id="wrapper">

			<div id="header" class="content-block">
				<section class="center">
					<div class="slogan">
						HandMadeReview
					</div>
					<div class="secondary-slogan">
						Share the pleasure of HandMadeWorks!
					</div>
					<div class="col-md-4 text-center">
							<div class="aboutus-item">
									<i class="aboutus-icon fa fa-android"></i>
									<h4 class="aboutus-title">Andorid</h4>
									<p class="aboutus-desc">Android版を近日公開予定</p>
							</div>
					</div>
          <!-- kokoni charracter -->
					<div class="you_movie">
						<iframe width="200" height="180" src="https://www.youtube.com/embed/rb_JuoBAnWw?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
					</div>
        <!-- kokoni maquee -->
				</section>
			</div><!-- header -->
			<!-- About us -->
	        <div id="about" class="about-us">
	            <div class="container about-sec">
	                <header class="block-heading cleafix">
							<div class="title-page">
								<p class="main-header">About This Site</p>
							    <p class="sub-header">For those who love HandMadeWorks</p>
							</div>
						</header>
	                <div class="divide50"></div>
	                <div class="row">
										<a href="/hm_reviews">
	                    <div class="col-md-4 text-center">
	                        <div class="aboutus-item">
	                            <i class="aboutus-icon fa fa-star"></i>
	                            <h4 class="aboutus-title">Reviews</h4>
	                            <p class="aboutus-desc">レビューの共有をして他の人に作品の魅力を伝えましょう！！</p>
	                        </div>
	                    </div>
										</a>
										<a href="/topics">
	                    <div class="col-md-4 text-center">
	                        <div class="aboutus-item">
	                            <i class="aboutus-icon fa fa-tasks"></i>
	                            <h4 class="aboutus-title">掲示板</h4>
	                            <p class="aboutus-desc">ハンドメイドに関連したことで話したいことがあれば気軽に話せます。</p>
	                        </div>
	                      </div>
											</a>
											<a href="/pages/relatednews">
		                    <div class="col-md-4 text-center">
		                        <div class="aboutus-item">
		                            <i class="aboutus-icon fa fa-wordpress"></i>
		                            <h4 class="aboutus-title">関連ニュース</h4>
		                            <p class="aboutus-desc">ハンドメイド関連のニュースが見れます。</p>
		                        </div>
		                    </div>
											</a>
	                </div>
	            </div>
	        </div>
	        <!-- /About us -->
		</div><!--/#wrapper-->
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails01App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/relatednews.html.erb
<p>関連ニュース</p>
coming soon
<br>
<p>
<%= link_to 'Home', root_path %>
</p>

app/views/responses/_form.html.erb
<%= form_with(model: response, local: true) do |form| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.name %></td>
        <td><%= response.body %></td>
        <td><%= response.created_at %></td>
        <td><%= response.updated_at %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @response.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @response.body %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @response.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @response.updated_at %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>スレッド一覧</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.created_at %></td>
        <td><%= topic.updated_at %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>スレッド新規作成</h1>
<%= form_for @newTopic, :url => {:action => 'create'} do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>


<%= link_to 'Home', root_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>
<br>
<p>
  <strong>レスポンス</strong>
</p>
<br>

<% if @responses != nil %>
<p>
  レスはあります
  <% @responses.each_with_index do |response , idx| %>
    <p>
      <%= idx + 1 %>. <%= response.name %> : <%= response.body %>
    </p>
  <% end %>
</p>
<% else %>
<p>レスが存在しません。</p>
<% end %>

<h3>新規書き込み</h3>
<%= form_for @newResponse, :url => response_create_path do |f| %>
  <p>お名前</p>
  <p><%= f.text_field :name %></p>
  <p>本文</p>
  <p><%= f.text_area :body %></p>
  <%= f.hidden_field :topic_id %>
  <%= f.submit %>
<% end %>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>
<%= link_to 'Home', root_path %>